### ISSUE TITLE
Fatal error: Exit code 1

### ISSUE THREAD

**Issue by bgruening** [CRG-Barcelona/bwtool#45]
With one of our 250 MB bigwig test files we get this error message:

```
Fatal error: Exit code 1 ()
errAbort re-entered due to out-of-memory condition. Exiting.
```

What does it mean? This process was able to allocate 30GB of memory.

**Comment by andypohl** [comment]
That's an error from the underlying library from Jim Kent / UCSC.  250 MB is a small bigWig but what is the genome size?  Writing bigWigs is a particularly heavy procedure for memory.  The bigWigCat (I think that's what it's called) is a program that will combine chromosome-sized (or smaller) bigWigs into a genome-sized one.  bigWigCat also introduced code into the JK/UCSC library for this purpose.  I never implemented the code bigWigCat uses in bwtool.  My workflow (and I was really busy with my own research) became processing data at the chromosome level on a cluster of computers and combining the results with bigWigCat.  It's really desirable to lower the memory footprint of bwtool for certain situations, but I'm still not sure what you're trying to do.  Which bwtool command were you attempting?

**Comment by bgruening** [comment]
@andypohl thanks for your answer. Genome size is mm10 and I try to create a few tests for the lift-over wrapper.

This is the command I'm running:
```
bwtool lift $input /data/db/reference_genomes/mm10/liftOver/mm10ToMm9.over.chain $output  -wigtype=var  -condense
```

**Comment by andypohl** [comment]
Yeah lifting is the most memory-intensive procedure.  I'm not surprised 30 GB is insufficient.  I guess the only thing I can suggest is to try doing it chromosome by chromosome... and that is not so intuitive the way I have it right now.  You have the data for mm10 and want it in mm9.  The bad part about lifting is that you need the full source dataset (mm10) for each run of bwtool.  And you'll need a size file for each chromosome of mm9  e.g.   "chr10.size", "chr2.size", etc.  Each of these files will be one line: the chromosome name in the first column and the size in the second.  Then, you'll run bwtool for each mm9 chromosome like this:

`bwtool lift $input mm10ToMm9.over.chain $output.chr.wig -wigtype=var -condense -wig-only`

You'll need the "-wig-only" because you need a special option to wigToBigWig to convert that to a bigWig compatible with bigWigCat.  I can find some more details about that.  I made a lot of use of that program in my research.  

I know it's clunky to make all these files.  It should really be a command-line option.  And it would be nice if bwtool made bigWigs compatible with bigWigCat right now.  Unfortunately without changing the bwtool program, that's the best suggestion I can think of.

**Comment by bgruening** [comment]
@andypohl increasing the memory did the trick. Interesting that this needs so much memory. Thanks!
