### ISSUE TITLE
Error when installing bwtool

### ISSUE THREAD

**Issue by sx-ruan** [CRG-Barcelona/bwtool#54]
I tried to install the latest version of bwtool locally:

git clone https://github.com/CRG-Barcelona/libbeato.git
git clone https://github.com/CRG-Barcelona/bwtool.git
cd libbeato/
./configure --prefix=$HOME CFLAGS="-g -O0 -I${HOME}/include" LDFLAGS=-L${HOME}/lib
make
make install
cd ../bwtool/
./configure --prefix=$HOME CFLAGS="-g -O0 -I${HOME}/include" LDFLAGS=-L${HOME}/lib
make
make install

But I kept getting the following error:

configure: error:
Unable to find libjkweb (libbeato)
required for compiling
bwtool. Install this and run ./configure
with the appropriate LDFLAGS/CFLAGS/etc.
See the INSTALL for examples.

I think it's caused by the latest update (May 31, 2017) of libbeato and bwtool, because there's no error when I tried to install bwtool using the previous versions of libbeato and bwtool.

**Comment by andypohl** [comment]
Right, sorry, I definitely reproduced this on linux.  The shared libraries produced when compiling libbeato have undefined symbols.  My Mac laptop uses clang instead of gcc, and this difference is enough to disrupt the build.  I was pretty sure I had tested the full compile on linux, but I probably stopped after making libbeato.  If I add `-Wl,-zdefs` to the `LDFLAGS` of `./configure`, I won't be able to produce a similar problematic shared library... it ends in a linking error.  I'm going to tinker around and if I can't get that to work really soon, I'll just roll back the changes.  In any case, the recent changes were only to the build system.  What you checked out and compiled from earlier should still be logically equivalent.

```
cd libbeato/
./configure 
```

**Comment by vincent625** [comment]
I have similar problem, where could I download previous version?

**Comment by andypohl** [comment]
I reverted bwtool and libbeato back to where they were 10 days ago. You should be able to compile according to the instructions.  Sorry for the problems and that I broke it.

I still intend to add the libtool-generated shared libraries, but I haven't quite finished fixing that.  Actually, it involved cleaning up a lot of the code from UCSC so I wouldn't have those undefined symbols.   I want the compile instructions to be as few steps as possible, but I think it's probably better to have libbeato and libjkweb separate, so that will be coming soon too.  In any case, I'll test the building more next time before I push code here.  Travis-CI is needed here.

**Comment by jacob3ke** [comment]
Hi Andy, 

I also tried to install the latest version of bwtool locally:

git clone https://github.com/CRG-Barcelona/bwtool.git
cd bwtool/
./configure


but finally i have met a problem just like the upstairs but with some difference:
   Unable to find zlib required for compiling
   bwtool. Install this and run ./configure
   with the appropriate LDFLAGS/CFLAGS/etc.
   See the INSTALL for examples.

how can I fix it? really Thanks!

**Comment by andreyeremin** [comment]
I have a problem installing bwtool on Mac OS Catalina, while running ./configure it says "configure: error: cannot run C compiled programs.", I tried two update gcc to the latest version, but it didn't work out. Can anyone help, please ?

**Comment by EasyPiPi** [comment]
Hi Andy,

I get the same error as jacob3ke and I'm running a Ubuntu 18.04 system.

```
configure: error: 
   ---------------------------------------------
   Unable to find zlib required for compiling
   bambed. Install this and run ./configure
   with the appropriate LDFLAGS/CFLAGS/etc.
   See the INSTALL for examples.
   ---------------------------------------------
```

I also tried to install zlib on my system but it says it's already installed.

`sudo apt install zlib1g`

Reading package lists... Done
Building dependency tree       
Reading state information... Done
**zlib1g is already the newest version (1:1.2.11.dfsg-0ubuntu2).**
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

Any clues for fixing it? Many thanks!
