### ISSUE TITLE
Segmentation fault  (core dumped)

### ISSUE THREAD

**Issue by alanzos** [CRG-Barcelona/bwtool#57]
Hello,

I have been using during the last days this command:
_bwtool extract bed $IN_FILE $BIGWIG $OUT_FILE_ 

And it has worked perfectly with all my different input files. However, for a particular file it gets this error:
_Segmentation fault (core dumped)_

The command I run is this:
_bwtool extract bed group_b_mutations.bed hg19.100way.phyloP100way.bw group_b_mutations_scores.bed_

Do you know why is this happening?

Thanks in advance!

Files are here:
[group_b_mutations_scores_bed.txt](https://github.com/CRG-Barcelona/bwtool/files/1790095/group_b_mutations_scores_bed.txt)  (bed file saved as TXT to be able to upload it here)
http://hgdownload.cse.ucsc.edu/goldenpath/hg19/phyloP100way/

Edit: the problem was with an entry in the input BED file, with length of 0.

**Comment by andypohl** [comment]
I'm glad you solved the problem, but segfaults are not descriptive error messages.  I will keep this in mind and try to fix that.  Actually my first choice would be to not have an error but allow the behavior i.e. empty inputs yielding empty outputs.  Sometimes that sort of flexibility promotes people having and keeping around weird data instead of addressing it like you have.  But I'm someone that really appreciates when a program doesn't fail because of small format issues.
